-- Script SQL PostgreSQL pour insérer les données des étudiants

-- Création de la table (optionnel - si elle n'existe pas déjà)
CREATE TABLE IF NOT EXISTS etudiants (
    id SERIAL PRIMARY KEY,
    niveau VARCHAR(5) NOT NULL,
    matricule VARCHAR(20) UNIQUE NOT NULL,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(150) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertion de toutes les données en une seule requête
INSERT INTO etudiants (niveau, matricule, nom, prenom, email) VALUES
('M1', '299H-TOL', 'ANDRIANANTENAINA', 'Claver Razafimandimby', 'claver.razafimandimby@email.com'),
('M1', '300H-TOL', 'ANDRIAMANARIVO', 'Lahiniriko', 'lahiniriko.andriamanarivo@email.com'),
('M1', '301H-TOL', 'ANDRIANAHARISON', 'Tsinjosoa Maharavo', 'tsinjosoa.maharavo@email.com'),
('M1', '302H-TOL', 'ANDRIANAIVOMANDAKA', 'Tahina Emmanuel Briallant', 'tahina.emmanuel@email.com'),
('M1', '303H-TOL', 'ANDRINAIVOSON', 'Mamy Mickael', 'mamy.mickael@email.com'),
('M1', '304H-TOL', 'ANDRIANJAFINOMBANA', 'Falinirina Ferdinand', 'falinirina.ferdinand@email.com'),
('M1', '307H-TOL', 'BOTOTSAKO', 'Romeo Augustin', 'romeo.augustin@email.com'),
('M1', '310H-TOL', 'FETISOA', 'Nomenjanahary Frezia Emeline', 'nomenjanahary.frezia@email.com'),
('M1', '312H-TOL', 'HANGISON', 'Fabien', 'fabien.hangison@email.com'),
('M1', '315H-TOL', 'HERITIANA', 'Delphino Claude', 'delphino.claude@email.com'),
('M1', '316H-TOL', 'RAHERIVELO', 'Andry Mijoro', 'andry.mijoro@email.com'),
('M1', '317H-TOL', 'JEAN', 'Christophe Mahalomba', 'christophe.mahalomba@email.com'),
('M1', '318H-TOL', 'JULLIOT', 'Andriamandraka', 'andriamandraka.julliot@email.com'),
('M1', '319H-TOL', 'LAHINIRIKO', 'Theodor', 'theodor.lahiniriko@email.com'),
('M1', '320H-TOL', 'MAMINIAINA', 'Solondrainy Hyancinthino', 'solondrainy.hyancinthino@email.com'),
('M1', '321H-TOL', 'MANJATIANA', 'Florida Safica', 'florida.safica@email.com'),
('M1', '322H-TOL', 'MBOLA', 'Odon', 'odon.mbola@email.com'),
('M1', '323H-TOL', 'NANTENAINA', 'Bertrand Victor', 'bertrand.victor@email.com'),
('M1', '325H-TOL', 'RAFANDEFERANA', 'Maminiaina Mercia', 'maminiaina.mercia@email.com'),
('M1', '326H-TOL', 'RAJOELINIRINA', 'Ifaliana Valitiana Lovasoa', 'ifaliana.valitiana@email.com'),
('M1', '328H-TOL', 'RAKOTOMALALA', 'Tolotriniaina Lionel', 'tolotriniaina.lionel@email.com'),
('M1', '329H-TOL', 'RAKOTONARIVO', 'Tiana Harivony', 'tiana.harivony@email.com'),
('M1', '330H-TOL', 'RANDRIAMAHASARO', 'Peter Advin', 'peter.advin@email.com'),
('M1', '331H-TOL', 'RANDRIANIRINA', 'Ramaherison Lucien', 'ramaherison.lucien@email.com'),
('M1', '332H-TOL', 'RASOLONIAINA', 'Arison Valencen', 'arison.valencen@email.com'),
('M1', '333H-TOL', 'RATOVONDILY', 'Tsiverilaza Prosper', 'tsiverilaza.prosper@email.com'),
('M1', '334H-TOL', 'RATSIANDAVANA', 'Mandranto Fitahiana', 'mandranto.fitahiana@email.com'),
('M1', '335H-TOL', 'RAZAFIMANDIMBY', 'Lionot', 'lionot.razafimandimby@email.com'),
('M1', '336H-TOL', 'RENAMBOHAJAINA', 'José Celestin', 'jose.celestin@email.com'),
('M1', '338H-TOL', 'SANTATRINIAINA', 'Maminirina William', 'maminirina.william@email.com'),
('M1', '339H-TOL', 'SAMBATRINIAINA', 'Marie Claudia', 'marie.claudia@email.com'),
('M1', '340H-TOL', 'SAMBATRA', 'Tahirindrazana', 'tahirindrazana.sambatra@email.com'),
('M1', '343H-TOL', 'TINAHY', 'François', 'francois.tinahy@email.com'),
('M1', '344H-TOL', 'TOHASOA', 'Tovoasy John Bien Aimé', 'tovoasy.john@email.com'),
('M1', '345H-TOL', 'TOLOJANAHARY', 'Josia Marie Néré', 'josia.marie@email.com'),
('M1', '349H-TOL', 'VIDY', 'Jean Thryce', 'jean.thryce@email.com'),
('M1', '351H-TOL', 'ANDRIAMIARISON', 'Mandaniaina Precieux', 'mandaniaina.precieux@email.com'),
('M1', '352H-TOL', 'ANDRIAMPARANY', 'Tata Kevin', 'tata.kevin@email.com'),
('M1', '353H-TOL', 'ANDRIATAHINA', 'Didier Herlin', 'didier.herlin@email.com'),
('M1', '354H-TOL', 'ANJAHERINIONY', 'René Amanda', 'rene.amanda@email.com'),
('M1', '362H-TOL', 'FULGENCE', 'Damivelo', 'damivelo.fulgence@email.com'),
('M1', '363H-TOL', 'MANAMBINTSOA', 'Heritiana Fiacre', 'heritiana.fiacre@email.com'),
('M1', '364H-TOL', 'MANANTSOA', 'Tsarafeno Elysé', 'tsarafeno.elyse@email.com'),
('M1', '367H-TOL', 'MIHAJASOA', 'Sarobidy Alfred Christiano', 'sarobidy.alfred@email.com'),
('M1', '368H-TOL', 'MIHOBISOA', 'Antsa Sarobidy Hardiot', 'antsa.sarobidy@email.com'),
('M1', '370H-TOL', 'NIRINDRAINY', 'Sylvano Albertin', 'sylvano.albertin@email.com'),
('M1', '371H-TOL', 'RABELAZA', 'Claude Elysé', 'claude.elyse@email.com'),
('M1', '372H-TOL', 'RADOMAHENINA', 'Tolotra Jacquinot', 'tolotra.jacquinot@email.com'),
('M1', '374H-TOL', 'RAHOASA', 'Tahina Marcellia', 'tahina.marcellia@email.com'),
('M1', '376H-TOL', 'RAKOTOZAFY', 'Nantanaina Jean De Dieu', 'nantanaina.jean@email.com'),
('M1', '378H-TOL', 'RAMARIELINA', 'Mirindra Kenny Branco', 'mirindra.kenny@email.com'),
('M1', '379H-TOL', 'RANAIVOSON', 'Jean De Dieu Dit Rodin', 'jean.dedieu@email.com'),
('M1', '381H-TOL', 'RANDRIANANDASANA', 'Aimé Felicien', 'aime.felicien@email.com'),
('M1', '383H-TOL', 'RANDRIANIRINA', 'Celson Gaetan', 'celson.gaetan@email.com'),
('M1', '384H-TOL', 'RASOAFIAVY', 'Lydia', 'lydia.rasoafiavy@email.com'),
('M1', '386H-TOL', 'RASANIRINA', 'Iarantsoa Francia', 'iarantsoa.francia@email.com'),
('M1', '387H-TOL', 'RATOLOJANAHARY', 'Fanilo Nantenaina', 'fanilo.nantenaina@email.com'),
('M1', '390H-TOL', 'RATSIMBAZAFY', 'Georges Mathaus', 'georges.mathaus@email.com'),
('M1', '391H-TOL', 'RATSIMBAZAFY', 'Fenohery', 'fenohery.ratsimbazafy@email.com'),
('M1', '392H-TOL', 'RAZAFIMAHATRATRA', 'Harinirina Angelica', 'harinirina.angelica@email.com'),
('M1', '393H-TOL', 'RAZAFINDRAIMINDRA', 'Ranjy Fiononana', 'ranjy.fiononana@email.com'),
('M1', '394H-TOL', 'RAZAFINDRAZANTA', 'Zinedine Vigilo', 'zinedine.vigilo@email.com'),
('M1', '395H-TOL', 'RAZAFINIAINA', 'Sylviane', 'sylviane.razafiniaina@email.com'),
('M1', '396H-TOL', 'RAZAFINIRINA', 'Elphège Benjamin', 'elphege.benjamin@email.com'),
('M1', '397H-TOL', 'REJELA', 'Fleria Razafindravelo', 'fleria.razafindravelo@email.com'),
('M1', '399H-TOL', 'SAROBIDY', 'Man San', 'man.san@email.com'),
('M1', '403H-TOL', 'TOLIANTANEE', 'Josette Marovavy', 'josette.marovavy@email.com'),
('M1', '405H-TOL', 'TSIMANAHY', 'Fanohiza Jonah Michel', 'fanohiza.jonah@email.com'),
('M1', '408H-TOL', 'ZANATSIORY', 'Fenohery Rollydia', 'fenohery.rollydia@email.com'),
('M2', '198H-TOL', 'ANDRIANJAKA', 'Raheliarison Ludovic', 'raheliarison.ludovic@email.com'),
('M2', '221H-TOL', 'RAHOASA', 'Nambinintsoa Abednego', 'nambinintsoa.abednego@email.com'),
('M2', '247H-TOL', 'ANDRIAMAZAORO', 'Mahenina Harifara', 'mahenina.harifara@email.com'),
('M2', '248H-TOL', 'ANDRIANASOLO', 'Herilanto Louis Denis', 'herilanto.louis@email.com'),
('M2', '249H-TOL', 'ANDRIANIRINA', 'Dilipkumar Vashi', 'dilipkumar.vashi@email.com'),
('M2', '250H-TOL', 'ANDRINIAINA', 'Marc Floris', 'marc.floris@email.com'),
('M2', '251H-TOL', 'ANJARASOA', 'Mamode Cristelle Sarah', 'mamode.cristelle@email.com'),
('M2', '252H-TOL', 'ASINDRAMINO', 'Sharon Constancia', 'sharon.constancia@email.com'),
('M2', '253H-TOL', 'ELIANDRAZA', 'Machut', 'machut.eliandraza@email.com'),
('M2', '256H-TOL', 'FANAROLAHY', 'Wilson Julien', 'wilson.julien@email.com'),
('M2', '257H-TOL', 'FANOMEZANTSOA', 'Bassir Olivio', 'bassir.olivio@email.com'),
('M2', '259H-TOL', 'FIDELICE', 'Rapizany', 'rapizany.fidelice@email.com'),
('M2', '260H-TOL', 'IMPALY', 'Joseph', 'joseph.impaly@email.com'),
('M2', '261H-TOL', 'LEKA', 'Yondo Patrick Zanzan', 'yondo.patrick@email.com'),
('M2', '264H-TOL', 'MANDROVELO', 'Samba Tendry Luco', 'samba.tendry@email.com'),
('M2', '267H-TOL', 'ONJASOA', 'Ornela Leonardine', 'ornela.leonardine@email.com'),
('M2', '268H-TOL', 'RAJOELSON', 'Tombarel Bertin', 'tombarel.bertin@email.com'),
('M2', '269H-TOL', 'RAJOHARISON', 'Iriantsoa Fiderana Ny Avo', 'iriantsoa.fiderana@email.com'),
('M2', '270H-TOL', 'RAKOTOARIMANANA', 'Hezaka', 'hezaka.rakotoarimanana@email.com'),
('M2', '273H-TOL', 'RAMAMBASOA', 'Rindralalaina Francine', 'rindralalaina.francine@email.com'),
('M2', '274H-TOL', 'RAMAMINIRINA', 'Victorino', 'victorino.ramaminirina@email.com'),
('M2', '276H-TOL', 'RANAIVOSON', 'Fanomezantsoa Eric', 'fanomezantsoa.eric@email.com'),
('M2', '277H-TOL', 'RANDRIAMARO', 'Andriamanalina Sandratra', 'andriamanalina.sandratra@email.com'),
('M2', '278H-TOL', 'RANDRIAMANAMBINA', 'Justino Christophe Kahike', 'justino.christophe@email.com'),
('M2', '279H-TOL', 'RANDRIANARIVO', 'Rojo Davida Richard', 'rojo.davida@email.com'),
('M2', '281H-TOL', 'RANDRIANJANAKA', 'Jean Tahina', 'jean.tahina@email.com'),
('M2', '283H-TOL', 'RASOANAMBININA', 'Maho Christine', 'maho.christine@email.com'),
('M2', '285H-TOL', 'RATOVOMISAOTRAHASINA', 'Israely Berthin', 'israely.berthin@email.com'),
('M2', '287H-TOL', 'RAVELOSON', 'Sylvain Lucky', 'sylvain.lucky@email.com'),
('M2', '290H-TOL', 'RAZAFINDRAHAZA', 'Anicet', 'anicet.razafindrahaza@email.com'),
('M2', '294H-TOL', 'ZAMBAZAFY', 'Bienvenue Larissa', 'bienvenue.larissa@email.com'),
('M2', '296H-TOL', 'TOVONIRINA', 'Hada Fabio', 'hada.fabio@email.com'),
('M2', '298H-TOL', 'ZONARIVO', 'Tahinisoa Manoela', 'tahinisoa.manoela@email.com')
ON CONFLICT (matricule) DO UPDATE SET
    niveau = EXCLUDED.niveau,
    nom = EXCLUDED.nom,
    prenom = EXCLUDED.prenom,
    email = EXCLUDED.email;

-- Vérification des insertions
SELECT 
    niveau,
    COUNT(*) as nombre_etudiants
FROM etudiants 
GROUP BY niveau 
ORDER BY niveau;

-- Affichage de quelques exemples
SELECT * FROM etudiants ORDER BY niveau, matricule LIMIT 10;