INSERT INTO etudiants (matricule, nom, prenom,niveau,email) VALUES
('442H-TOL','MAMINIAINA','Stephanie','L3',''),
('498H-TOL','TSILEFERANTSOA','Rolland Siuol','L3',''),
('448H-TOL','MIHARISOA','Claricette louiyah Maximine','L3',''),
('475H-TOL','RASOLOZANDRY','Lalatiana','L3',''),
('465H-TOL','RAMAMONJISOA','Eric Chrisophere','L3',''),
('452H-TOL','NAMBININJANAHARY','Safidy Sylvana','L3',''),
('474H-TOL','RASOAVELONANTENAINA','Sitraka Marius','L3',''),
('493H-TOL','TATIANA','Volasoa Gisèle','L3',''),
('481H-TOL','RAZAFIMAMONJY','Fanomezantsoa Heurio Fortunat','L3',''),
('449H-TOL','MILAMANA','Darcy','L3',''),
('473H-TOL','RASOANANJARA','Nalisoa Judia Lambert','L3',''),
('457H-TOL','RABEASY','Mamy Tatiana','L3',''),
('499H-TOL','TSIMAGNEFEDRAZA','Solomon','L3',''),
('497H-TOL','TODISOA','Joseph Navony','L3',''),
('464H-TOL','RAKOTOMALALA','Serginot Pirès Règis','L3',''),
('458H-TOL','RABENARISON','Bien Christophe','L3',''),
('503H-TOL','ZAFIMANOELA','Mahavotsy Romeo','L3',''),
('423H-TOL','ANTOKA','Dunamis Tsihazoa','L3',''),
('437H-TOL','LAHINIRIKO','Fitahiana Helmine','L3',''),
('308H-TOL','EXDOUZEA','Bien Aimé','L3',''),
('486H-TOL','RAZAFIMANANTSOA','Onjaniaina Loic','L3',''),
('444H-TOL','MANANTENA','Faustin','L3',''),
('495H-TOL','TIVERNE','Solonomena Stéphane','L3',''),
('439H-TOL','LANJANALAHATSE','Aggio Kevin','L3',''),
('418H-TOL','ANDRIANIAIVOSON','Hariniaina Thierry','L3',''),
('446H-TOL','MARCEL','Alyh Lorniot','L3',''),
('416H-TOL','ANDRIAMIHAJA','Jean Romario','L3',''),
('417H-TOL','ANDRIANAIVOMIARANA','Ambinintsoa Fenitriniaina','L3',''),
('462H-TOL','RAHARIMANANA','Mariot Fanantenana','L3',''),
('466H-TOL','RAMANANTENASOA','Santatra Niriniony','L3',''),
('501H-TOL','TSITOHERY','Lahivao Androssy','L3',''),
('369H-TOL','MONJA','Marcel','L3',''),
('424H-TOL','AVOFAHEVAMIRATRINIAINA','Jocaya Elsevline','L3',''),
('438H-TOL','LAKORIJA','Mario Gracia','L3',''),
('415H-TOL','ANDRIAMAHADY','Hasiniaina','L3',''),
('471H-TOL','RANDRIANAMBININA','Jacob Bless','L3',''),
('470H-TOL','RANDRIAMIHAJA','Lovasoa','L3',''),
('476H-TOL','RATOAVINJANAHARY','Jean Raymond','L3',''),
('419H-TOL','ANDRIANARIVO,Marson Vorilaza','L3',''),
('453H-TOL','NANTENAINA','Marentane Sambo Angelo','L3',''),
('490H-TOL','SAROBIDY','Francesca Edminsen','L3',''),
('420H-TOL','ANDRIANASOLO','Andriamanendrika Safidy','L3',''),
('488H-TOL','LOVASOANOMENJANAHARY','Hasina','L3',''),
('451H-TOL','MITOVIMANA','Emmanoel','L3',''),
('461H-TOL','RAHARIMANANA','Brayann Juanico Duhard','L3',''),
('479H-TOL','RAZAFIARISOA','Eddiene Lorizia','L3',''),
('434H-TOL','JAONARIVELO','Rovaniaina Leonce','L3',''),
('407H-TOL','VORIANDRO,Tahindrainy Clarène','L3',''),
('443H-TOL','MAMPITOFOTSE','Jean Mesmino','L3',''),
('478H-TOL','RAVELOMANANTSOA','Nantenaina Sitraka','L3',''),
('467H-TOL','RAMBININTSOA','Flavien Alfred','L3',''),
('429H-TOL','FANASINA','Mickael','L3',''),
('337H-TOL','ROBENA','Marus Prudent','L3',''),
('469H-TOL','RAMIADANTSOA','Ibrahum Asraf Xavier','L3',''),
('433H-TOL','HASINIAINA','Safidisoa Gilbert','L3',''),
('502H-TOL','VAHIA','Jean Cristian Rivaldo','L3',''),
('428H-TOL','FAHASOAVAMPANANTENANA','Manda Nehemia','L3',''),
('430H-TOL','FANOMEZANTSOA','Nomenjanahary Elina','L3',''),
('455H-TOL','ODONARDO','Desiré Andriamiadana Avenir Retsala','L3',''),
('496H-TOL','TOGNENDRAZA','Ravalomanana Francis Bien-Aimé','L3',''),
('480H-TOL','RAZAFIMAHATRATRA','Lahiniriko Armand Licko','L3',''),
('485H-TOL','RAZATSIALAINA','Roux De Paxton','L3',''),
('421H-TOL','ANDRIANJARA','Jean De bristten','L3',''),
('431H-TOL','FENOHARILALA','Jean Felix','L3',''),
('426H-TOL','DJASCHA','Djaphar','L3',''),
('491H-TOL','SOLOFONAMBININA','Marcelia','L3',''),
('500H-TOL','TSIRAVAE','Radoko','L3',''),
('435H-TOL','JEAN','Aimé Rafidison','L3',''),
('477H-TOL','RAVELOGNANDRO','Nirina Albertho','L3',''),
('436H-TOL','JOVIN','Zafiniriko Assaly','L3',''),


('611H-TOL','ALISOA','Fantatra Jeannah','L1',''),
('612H-TOL','AMBININTSOA','Drà Marcello','L1',''),
('613H-TOL','ANDRIAMAHOLY','Zoara Sendra Fandresena','L1',''),
('614H-TOL','ANDRIAMAMPAHERY','Abednego Josephat','L1',''),
('615H-TOL','ANDRIAMANANTSOA','Maharavo Elie Hervé','L1',''),
('616H-TOL','ANDRIAMANIFA,R . Kelly Josvah','L1',''),
('617H-TOL','ANDRIANJAFINIRINA','Santatraniaina','L1',''),
('618H-TOL','ANDRIANOELSON','Notahinjanahary Fifaliana','L1',''),
('619H-TOL','ANDRIAZAFIMANDRAKA','Tsiahy Roddy','L1',''),
('620H-TOL','ARITRINIAINA','Ravily Philibert','L1',''),
('621H-TOL','ARONIAIKO','Adolphe Francois','L1',''),
('622H-TOL','BERA','Andriadelina Edwige','L1',''),
('623H-TOL','BEZARA','Mamenoaina Njaka Foiavo Emmanuel','L1',''),
('624H-TOL','BRUNO','Paul Manahake','L1',''),
('625H-TOL','CALVIN','Nomenjanahary Rosseto Gabriel','L1',''),
('626H-TOL','DAMY','Ratsirambesy Lazamana Nirina','L1',''),
('627H-TOL','DIMBIARISON','Lota Sohny','L1',''),
('628H-TOL','EMAHAFARY','José Bievenu','L1',''),
('629H-TOL','ETSIHOVOTSE','Hommeguy Ineramoun lapphlot','L1',''),
('630H-TOL','FABRICE','Bellarmand Celion','L1',''),
('631H-TOL','FANIRIKONOMENJANAHARY','Angio Marcelin','L1',''),
('632H-TOL','FANOMEZANTSOA','Sarobidy Arondrainy','L1',''),
('633H-TOL','FETRA','Rajoasitera','L1',''),
('634H-TOL','HAINGOTIANA','Manuela','L1',''),
('635H-TOL','HAJASON','Patrick Norsah Quentin','L1',''),
('636H-TOL','HASINIAINA','Anna Mercia Josiane Severin','L1',''),
('637H-TOL','HASOLOTSIRAVA','Mercino','L1',''),
('638H-TOL','JAONA','EL Elroy Laurent Fils','L1',''),
('639H-TOL','KABILA','Herilaza Elisé','L1',''),
('640H-TOL','LAHINIRIKO','Donis Frank Pierre Celestin','L1',''),
('641H-TOL','LAHINIRINA','Fidolin Rezotse','L1',''),
('642H-TOL','LEMBASON','Sitraka Lalaina','L1',''),
('643H-TOL','MAHATRANGA','Patrick','L1',''),
('644H-TOL','MANDRAKA','Fabien Frose Patrick','L1',''),
('645H-TOL','MAROTOMBO','Albert','L1',''),
('646H-TOL','MBOLAVERSENE','Hanolitane Jean Baptiste','L1',''),
('647H-TOL','NANTENAINA','Rosali n Mario','L1',''),
('648H-TOL','NOMENJANAHARY','Benjamina','L1',''),
('649H-TOL','ONJANDRIANINA','Claudeven Yriana','L1',''),
('650H-TOL','PASCO','Gasparol Mahafilo','L1',''),
('651H-TOL','RABENASOLO','Andrianandraina Josoa','L1',''),
('652H-TOL','RAHARINIAINA','Cedric Vestephan','L1',''),
('653H-TOL','RAHERIMALALA','Anjaniaina Tatiana','L1',''),
('654H-TOL','RAJAOBELINA','Efaliany Aldine','L1',''),
('655H-TOL','RAJAONARY','aina BENJAMINA André','L1',''),
('656H-TOL','RAKOTOMALALA','Tecle Chrisos','L1',''),
('657H-TOL','RAKOTOSON','Princesse Emelie Alison','L1',''),
('658H-TOL','RALAININDRINA','Noella','L1',''),
('659H-TOL','RALAIVAOTSIRESILAZA','Hoby Fanekena','L1',''),
('660H-TOL','RAMAMBASOA','Sandra Josephine Fitiavana','L1',''),
('661H-TOL','RAMAMBASOA','Sitrakiniaina Maminineny Francine','L1',''),
('662H-TOL','RAMANANJANAHARY','Zafimandimby Berthine','L1',''),
('663H-TOL','RAMAROLAHY','Vavinirina Bernadette','L1',''),
('664H-TOL','RANAIVOSOLO','sahala Luxana','L1',''),
('665H-TOL','RANAIVOMANANA','Filigene Francky Michel','L1',''),
('666H-TOL','RANDRENIMIADANA','Augustin Salomon','L1',''),
('667H-TOL','RANDRIAMASINORO','Sitraniavo Eric','L1',''),
('668H-TOL','RANDRIANANDRASANA','Fahasoavana Emmanuel','L1',''),
('669H-TOL','RANDRIANANDRASANA','Rakotoson Edlin','L1',''),
('670H-TOL','RANDRIATSITOHAINA','Tsimamandro Feno','L1',''),
('671H-TOL','RASOANANDRASANA','Bénédicte Désirée','L1',''),
('672H-TOL','RATAFIKA','Illa','L1',''),
('673H-TOL','RATSIMBAZAFY','Siara Josinah Lianah','L1',''),
('674H-TOL','RAVELONANDRO','Marie Patience','L1',''),
('675H-TOL','RAVELOSOA','Jeanne Patricia','L1',''),
('676H-TOL','RAZAFIMAMPIONONA','Andoniaina Nichel','L1',''),
('677H-TOL','RAZAFIMANDIMBY','Aimerancienne Michaella Lucianah','L1',''),
('678H-TOL','RAZAFIMANDIMBY','Perline Lovasoa','L1',''),
('679H-TOL','RAZAFINANDRASANA','Henrieldyno Bon santé Manampindrainy','L1',''),
('680H-TOL','RAZAFINDRAIBE','Elidah','L1',''),
('681H-TOL','RAZAFINDRAVAHY','Miangolanarivo','L1',''),
('682H-TOL','RAZAFINIRINA','Michaylah Martial','L1',''),
('683H-TOL','RAZAFITSARA','Audrey Olivier','L1',''),
('684H-TOL','REMANDIETSE','Tokisoa','L1',''),
('685H-TOL','RISITE','Bolivar Flobert','L1',''),
('686H-TOL','SAVANA','Georgette','L1',''),
('687H-TOL','SOAVANASANDRATRA','Lazarich Elilyno','L1',''),
('688H-TOL','TODISOA','Heriniaina Francia Esther','L1',''),
('689H-TOL','TOLOJANAHARY','Francis','L1',''),
('690H-TOL','TONENTSOA','Léontine','L1',''),
('691H-TOL','TOVONTSOA','Patrice','L1',''),
('692H-TOL','TSIAMBAHAKO','Fandresena Anthony','L1',''),
('693H-TOL','TSIANDARIZAFIMAMPIANDRA','Manampily','L1',''),
('694H-TOL','TSITAKE','Tinahindraza Tatianah','L1',''),
('695H-TOL','TSITSOBO','Valentin de Venance','L1',''),
('696H-TOL','VELOSOA','Angelot Narcisse','L1',''),
('697H-TOL','VELOTAHINA','José Antolin','L1',''),
('698H-TOL','VOATAHINDRAINY','Alexandro Henri','L1',''),
('699H-TOL','VOHORAZA','Voatsapa','L1',''),
('700H-TOL','VOLAMIHANTA','Mitondrasoa Man San','L1',''),
('701H-TOL','ZAFIMARY','Soary Daniellie Claritah','L1',''),
('702H-TOL','ZAFINDREVELO','Gabeline Justine','L1',''),
('703H-TOL','ZENERALY','Guillaume Horace','L1',''),
('704H-TOL','RAMAHANDRIVELO','Ron Cedrick','L1',''),
('705H-TOL','MIHA','Hervé','L1',''),
('456H-TOL','ONITRARIZAKA','Yvan Willius','L2',''),
('441H-TOL','MAMELSON','Jean Christian','L2',''),
('445H-TOL','MANDIMBISON','Sitrick','L2',''),
('482H-TOL','RAZAFIMAMONJY','Francio Anthony','L2',''),
('492H-TOL','SOVENY','Rasoanandrasana Sarah','L2',''),
('506H-TOL','RANDRIANTSITOHAINA','Ravoniaina','L2',''),
('508H-TOL','RAZAFIMANANTSOA','Charles Ryan','L2',''),
('509H-TOL','RABARINARIVO','Onja Milanto','L2',''),
('510H-TOL','RANDRIANANTOANDRO','Efototsafe Sylvano','L2',''),
('511H-TOL','TIRISOA','Samsia ibrahim','L2',''),
('512H-TOL','RATOVOARIVONY','Mathias','L2',''),
('513H-TOL','ANTOINI','Ahmed','L2',''),
('514H-TOL','TSIAHIFIKY','Fidson','L2',''),
('515H-TOL','MANAHIRA','Norlande Hubert','L2',''),
('517H-TOL','RAVELONJANAHARY','Harena Jessica','L2',''),
('518H-TOL','RABEARIVONY','Andoniaina Rianala Josia','L2',''),
('520H-TOL','TANTELY','Madie Simon','L2',''),
('521H-TOL','RASOANANDRASANA','Daudea Régis','L2',''),
('522H-TOL','ELI','Richard Seraly','L2',''),
('523H-TOL','RANDRIANANTENAINA','Martialino','L2',''),
('525H-TOL','RAMANAMANJATO','NY Aina Hasindrainibe','L2',''),
('527H-TOL','SITRA','Nomendraza Rider','L2',''),
('528H-TOL','FANOMEZANTSOA','Dimby Lalaina Toavina','L2',''),
('529H-TOL','RANAIVOSON','Anthony','L2',''),
('530H-TOL','TOLOJANAHARY','Stephan','L2',''),
('531H-TOL','FITAHIA','Hantonako Jonathan','L2',''),
('532H-TOL','FILANTSOA','Jacquis Marcellin','L2',''),
('533H-TOL','YANN','Julien','L2',''),
('534H-TOL','RASOLONDRAIBE','Andrianitiana Bienvenue','L2',''),
('535H-TOL','IALIMIHAJA','Fenotoky Juvenal','L2',''),
('536H-TOL','RAKOTOMAMINIRINA','Fanomezaniavo Fenohery','L2',''),
('538H-TOL','RAMANANJANAHARY','Francisco Elphege','L2',''),
('539H-TOL','TOLOJANAHARY','Mamy Urside Daniel khonné','L2',''),
('540H-TOL','ANDRIANIRINA','Andoniaina Orlando','L2',''),
('541H-TOL','LAHIMIARO','Georges Christian','L2',''),
('542H-TOL','RANDRIAMIARIJAONA','Jean Bosco','L2',''),
('543H-TOL','TOVONDRAINY','Jean Rodrique','L2',''),
('544H-TOL','NOMENJANAHAY','Victorio Emile','L2',''),
('545H-TOL','ANDRIAMALALA','Maleck Cedric','L2',''),
('546H-TOL','HERILALA','Hubert Ginola','L2',''),
('547H-TOL','MAHENE','Andrianjaka CIvanoT','L2',''),
('548H-TOL','LAHINANDRASANA','Zico Jonarson','L2',''),
('549H-TOL','BABAY','Rayan','L2',''),
('550H-TOL','LAKORIJA','Nantenaina mel-Nazir','L2',''),
('551H-TOL','ROLLANDO','Jean Bajio','L2',''),
('552H-TOL','ANDRIANIAINA','Florant Buchat','L2',''),
('553H-TOL','FAHAMARO','Tovondraza Victor','L2',''),
('554H-TOL','RAZAFINDRABE','Jean Nestin','L2',''),
('556H-TOL','HERINJANAHARY','Zafin-drengoky Farihimaminiaina Florent','L2',''),
('557H-TOL','RATSIRAVAINA','Derandraibe','L2',''),
('558H-TOL','RAVELOSAMBATRA','Tojo Safidy Elyot','L2',''),
('559H-TOL','RAKOTONANDRASANA','Jean julyot','L2',''),
('560H-TOL','EMAHAFEHY','Lahimasy Prosper David','L2',''),
('561H-TOL','ANDRIATSIMIOVA','Tovonay Dillane','L2',''),
('562H-TOL','ANDRIAMANGASON','Solofoniaina Daniello','L2',''),
('563H-TOL','YARASSA','Vaonomeny Tiarison','L2',''),
('564H-TOL','FANIRIANTSOA','Avotriniaina','L2',''),
('565H-TOL','FANIRIANTSOA','Jacques Roberthos','L2',''),
('566H-TOL','RANDRIANIRINA','Franco','L2',''),
('567H-TOL','ANDRIMAMPIONONA','Fanomezantsoa Emmanuel','L2',''),
('568H-TOL','RASOLONANDRASANA','Tafita Rabeony','L2',''),
('569H-TOL','MAMENOFO','Tiavina Anjara Victor Emmanuel','L2',''),
('570H-TOL','MALAKIA','Tody Faniriantsoa Fitsara','L2',''),
('571H-TOL','ORNELLA','Claudia','L2',''),
('572H-TOL','MBOLA','Tsimahory Tolivoatse','L2',''),
('573H-TOL','RAFANOMEZANTSOA','Olivier Michel','L2',''),
('574H-TOL','ANDRIANANJA','Sedraniaina Herilando','L2',''),
('577H-TOL','ANDRIANJATONIRINA','Ony Fenitra','L2',''),
('578H-TOL','RALAIVAOTSIRESILAZA','Antso Feon ny Fahasoavana','L2',''),
('580H-TOL','RODIN','Rucky Jaerolà','L2',''),
('582H-TOL','RAMANAMITAHY','Manantsolo Pascal','L2',''),
('583H-TOL','NEKENJANAHARY','Fifaliana Angelos','L2',''),
('584H-TOL','SAHIB,Henri Mortouza','L2',''),
('585H-TOL','RATEFIARISON','Albertino Christophe','L2',''),
('586H-TOL','MAZOTO','Kevin-jio','L2',''),
('587H-TOL','RAVONIAINA','Romuald','L2',''),
('588H-TOL','VELONTSOA','Cedric Dumont','L2',''),
('589H-TOL','RAZAFINDRAIMINDRA','Mampionona Rakotovao','L2',''),
('592H-TOL','LANDO','Julien','L2',''),
('593H-TOL','BRITTINAH','Gabriella Larsiah','L2',''),
('594H-TOL','RABOBASON','Marius Rockefeller','L2',''),
('595H-TOL','RANDRIATINA','Jeanne Iharinantenaina','L2',''),
('596H-TOL','FANAMPISOA','Jean Chrysostome','L2',''),
('597H-TOL','TAHINJANAHARY','Fredo','L2',''),
('599H-TOL','FLEURE','Bella Pageot','L2',''),
('600H-TOL','TOHAMANOARISON','Jean Sartavaly','L2',''),
('602H-TOL','NOMENJANAHARY','Martela Bruno','L2',''),
('603H-TOL','RAZAFIMANDIMBY','Herllandys Amoros christy','L2',''),
('604H-TOL','ANDRIAMALAZANTSOA','Tongalaza Amm-don','L2',''),
('605H-TOL','RANOMENJANAHARY','Njara Paulette','L2',''),
('606H-TOL','RAHARINIRINA','Tahintsoa Juvance','L2',''),
('607H-TOL','LANJAKO','Fenoanjara Chancette Claudine','L2',''),
('609H-TOL','RATOVOARISON','Solofonantenaina Claude','L2',''),
('299H-TOL','ANDRIANANTENAINA','Claver Razafimandimby','M1',''),
('300H-TOL','ANDRIAMANARIVO','Lahiniriko','M1',''),
('301H-TOL','ANDRIANAHARISON','Tsinjosoa Maharavo','M1',''),
('302H-TOL','ANDRIANAIVOMANDAKA','Tahina Emmanuel Briallant','M1',''),
('303H-TOL','ANDRINAIVOSON','Mamy Mickael','M1',''),
('304H-TOL','ANDRIANJAFINOMBANA','Falinirina Ferdinand','M1',''),
('307H-TOL','BOTOTSAKO','Romeo Augustin','M1',''),
('310H-TOL','FETISOA','Nomenjanahary Frezia Emeline','M1',''),
('312H-TOL','HANGISON','Fabien','M1',''),
('315H-TOL','HERITIANA','Delphino Claude','M1',''),
('316H-TOL','RAHERIVELO','Andry Mijoro','M1',''),
('317H-TOL','JEAN','Christophe Mahalomba','M1',''),
('318H-TOL','JULLIOT','Andriamandraka','M1',''),
('319H-TOL','LAHINIRIKO','Theodor','M1',''),
('320H-TOL','MAMINIAINA','Solondrainy Hyancinthino','M1',''),
('321H-TOL','MANJATIANA','Florida Safica','M1',''),
('322H-TOL','MBOLA','Odon','M1',''),
('323H-TOL','NANTENAINA','Bertrand Victor','M1',''),
('325H-TOL','RAFANDEFERANA','Maminiaina Mercia','M1',''),
('326H-TOL','RAJOELINIRINA','Ifaliana Valitiana Lovasoa','M1',''),
('328H-TOL','RAKOTOMALALA','Tolotriniaina Lionel','M1',''),
('329H-TOL','RAKOTONARIVO','Tiana Harivony','M1',''),
('330H-TOL','RANDRIAMAHASARO','Peter Advin','M1',''),
('331H-TOL','RANDRIANIRINA','Ramaherison Lucien','M1',''),
('332H-TOL','RASOLONIAINA','Arison Valencen','M1',''),
('333H-TOL','RATOVONDILY','Tsiverilaza Prosper','M1',''),
('334H-TOL','RATSIANDAVANA','Mandranto Fitahiana','M1',''),
('335H-TOL','RAZAFIMANDIMBY','Lionot','M1',''),
('336H-TOL','RENAMBOHAJAINA','José Celestin','M1',''),
('338H-TOL','SANTATRINIAINA','Maminirina William','M1',''),
('339H-TOL','SAMBATRINIAINA','Marie Claudia','M1',''),
('340H-TOL','SAMBATRA','Tahirindrazana','M1',''),
('343H-TOL','TINAHY','François','M1',''),
('344H-TOL','TOHASOA','Tovoasy John Bien Aimé','M1',''),
('345H-TOL','TOLOJANAHARY','Josia Marie Néré','M1',''),
('349H-TOL','VIDY','Jean Thryce','M1',''),
('351H-TOL','ANDRIAMIARISON','Mandaniaina Precieux','M1',''),
('352H-TOL','ANDRIAMPARANY','Tata Kevin','M1',''),
('353H-TOL','ANDRIATAHINA','Didier Herlin','M1','didierherlin18@gmail.com'),
('354H-TOL','ANJAHERINIONY','René Amanda','M1',''),
('362H-TOL','FULGENCE','Damivelo','M1',''),
('363H-TOL','MANAMBINTSOA','Heritiana Fiacre','M1',''),
('364H-TOL','MANANTSOA','Tsarafeno Elysé','M1',''),
('367H-TOL','MIHAJASOA','Sarobidy Alfred Christiano','M1',''),
('368H-TOL','MIHOBISOA','Antsa Sarobidy Hardiot','M1',''),
('370H-TOL','NIRINDRAINY','Sylvano Albertin','M1',''),
('371H-TOL','RABELAZA','Claude Elysé','M1',''),
('372H-TOL','RADOMAHENINA','Tolotra Jacquinot','M1',''),
('374H-TOL','RAHOASA','Tahina Marcellia','M1',''),
('376H-TOL','RAKOTOZAFY','Nantanaina Jean De Dieu','M1',''),
('378H-TOL','RAMARIELINA','Mirindra Kenny Branco','M1',''),
('379H-TOL','RANAIVOSON','Jean De Dieu Dit Rodin','M1',''),
('381H-TOL','RANDRIANANDASANA','Aimé Felicien','M1',''),
('383H-TOL','RANDRIANIRINA','Celson Gaetan','M1',''),
('384H-TOL','RASOAFIAVY','Lydia','M1',''),
('386H-TOL','RASANIRINA','Iarantsoa Francia','M1',''),
('387H-TOL','RATOLOJANAHARY','Fanilo Nantenaina','M1',''),
('390H-TOL','RATSIMBAZAFY','Georges Mathaus','M1',''),
('391H-TOL','RATSIMBAZAFY','Fenohery','M1',''),
('392H-TOL','RAZAFIMAHATRATRA','Harinirina Angelica','M1',''),
('393H-TOL','RAZAFINDRAIMINDRA','Ranjy Fiononana','M1',''),
('394H-TOL','RAZAFINDRAZANTA','Zinedine Vigilo','M1',''),
('395H-TOL','RAZAFINIAINA','Sylviane','M1',''),
('396H-TOL','RAZAFINIRINA','Elphège Benjamin','M1',''),
('397H-TOL','REJELA','Fleria Razafindravelo','M1',''),
('399H-TOL','SAROBIDY','Man San','M1',''),
('403H-TOL','TOLIANTANEE','Josette Marovavy','M1',''),
('405H-TOL','TSIMANAHY','Fanohiza Jonah Michel','M1',''),
('408H-TOL','ZANATSIORY','Fenohery Rollydia','M1',''),
    niveau = EXCLUDED.niveau,
    nom = EXCLUDED.nom,
    prenom = EXCLUDED.prenom,
    email = EXCLUDED.email;